### ISSUE TITLE
brainstorm

### ISSUE THREAD

**Issue by MasseGuillaume** [MasseGuillaume/ScalaKata#18]
### Modes
- sandbox
- presentation
- tour
### Concepts
- [gitbook](http://gitbookio.gitbooks.io/javascript/numbers/advanced.html) little Q&A exercices
- [library doc](http://moro.wolfe.ml:9000/doc/wolfe-static/wolfe/docs/concepts/01_worlds)
- [...](https://github.com/jas/swift-playground-builder)

**Comment by vramana** [comment]
Have you seen the Swift Playground in Xcode6 beta?? Adjoining the output value right next to code sometimes felt cluttered to me. What are your thoughts?

**Comment by MasseGuillaume** [comment]
yep I saw the playground in the demo presentation. Now the insight is on the next line, it's not much better but at least the code and the insight don't overlap.
