### ISSUE TITLE
Scalakata hangs on code with App trait

### ISSUE THREAD

**Issue by lazyval** [MasseGuillaume/ScalaKata#2]
Here is the minimal example.

```
object Main extends App {
    val name = "Greg"
}

println("Name: "+Main.name)
```

The code with usual object works fine.
When I'm hitting green button it becomes unavailable and then (after a few seconds) I get this alert: 

![514c40eae4b03969a614d85e](https://f.cloud.github.com/assets/235297/290461/2625dad8-92e4-11e2-9c90-ed0f3520b6de.png)

I'm using OSX 10.8.3 and Chrome 25.0.1364.172

**Comment by MasseGuillaume** [comment]
It's because the scala interpreter does not have acces to the Platform
scala.MatchError: java.lang.NoClassDefFoundError: Could not initialize class scala.compat.Platform$ 

check: http://www.scalakata.com/514c7a27e4b0d323913d1f5f
