### ISSUE TITLE
Embedding ScalaKata

### ISSUE THREAD

**Issue by ghost** [MasseGuillaume/ScalaKata#3]
Hi
I'm experimenting with some ideas on Scala teaching (see [here](http://www.reddit.com/r/scala/comments/1iikhr/help_building_a_scala_tutorials_community_site/))  

one of my first goals was to do something like ["a tour of go"](http://tour.golang.org/#1)
e.g. a sequence of editable and runnable code examples.

One idea was to use the Scala JS experimental support, but the drawback is ~20MB of JS for the Scala runtime. 

Then a friend of mine shared the link to ScalaKata. I was more than impressed! it runs amazingly fast, and looks great. 
I was looking for "about" or contact information and couldn't found. So I was happy to find you here in GH. 

So my question is this - I would love to use ScalaKata for this tour. the idea is to create about 20 fixed examples and share them using an iframe on scalatutorials.com and to do so I feel I need your permission of course! 

I noticed you have a jQuery plugin, and also that you support cross origin requests, so I was wondering if I can get your (conditional, revoke at any time) permission to use it for experiments on scalatutorials.com. I will put credit in any wording / location you would like of course / add any license / legal etc you want.

At the moment the site has 0 traffic so it's just for experimenting.

Here are the options I thought of, please let me know which one is OK with you.

(For the "tour of Scala") 
1. a few scalakata fixed snippets in iframes (will have "powered by Scalakata.com in the bottom") 
2. or using your scala api endpoint using your jquery plugin (less requests perhaps)
3. forking and running scalakata on my own servers (with attribution to you)

Are any of the above OKwith you? feel free to condition it with # of requests / traffic.

I think you did an amazing thing with ScalaKata, and would love to get your OK!

Thanks!

Eran (eranation at GH)

**Comment by MasseGuillaume** [comment]
Hey Eran,

I'm really glad you liked it.

ScalaJS has great potential but it will not support java so some libs wont work. For the long term, I think it's better in term of scalability / being able to work offline. 

Meanwhile, I created scalakata so people could use it, so feel free to use it without restriction as is. I run on a free setup with cloudbees.com and mongolab.com I currently have more than 25 000 evaluations.

for scalatutorial I can help you :-). I think you should avoid I frames :P and use the jquery plugin. If you want, we can have a video call during the weekend. i'm mas gui at gmail

**Comment by scalatutorials** [comment]
This is great! very much appreciated, the minute it becomes a burden on your host billing, let me know :)
Will _love_ to have you help on scalatutorials! a video call sounds great, will send you a note by email 
Thanks!
