### ISSUE TITLE
Focus on page load

### ISSUE THREAD

**Issue by jedesah** [MasseGuillaume/ScalaKata#4]
On OS X 10.8.4, with Chrome v28, the cursor doesn't automatically focus on the editor after loading.

It would be nice if it did since the main reason to navigate to scalakata.com is to start typing some Scala code as soon as possible.

**Comment by MasseGuillaume** [comment]
https://github.com/MasseGuillaume/ScalaKata/blob/89c838515bf397cb08a69999fc9401747cd13b0e/src/main/webapp/templates-hidden/kata.html#L3
