### ISSUE TITLE
Windows - macro annotation could not be expanded (... macro paradise plugin; ... )

### ISSUE THREAD

**Issue by amitsudharshan** [MasseGuillaume/ScalaKata#46]
I'm running scala 2.11, and followed the instructions for adding scalakata to my build.sbt. 
I get an error when trying to run the following instruction in the browser:

3 *3
macro annotation could not be expanded (the most common reason for that is that you need to enable the macro paradise plugin; another possibility is that you try to use macro annotation in the same compilation run that defines it)

Any ideas?

**Comment by MasseGuillaume** [comment]
are you on Window?

**Comment by amitsudharshan** [comment]
Yes :(

**Comment by MasseGuillaume** [comment]
It's an issue with the arguments passed in the fork. This message means that the compiler dont have access to the macro paradise plugin. This come from scalacOptions in Kata. I'm not 100% sure this is the issue.

I don't have time to fix this now. I'm pointing the possible lines that could go wrong. If you wish to fix it yourself, It would be really cool.

Plugin
https://github.com/MasseGuillaume/ScalaKata/blob/753f841fa149fe3c0c58fe3fc16d06aef8215afc/Plugin/src/main/scala/com.scalakata/ScalaKata.scala#L100
https://github.com/MasseGuillaume/ScalaKata/blob/753f841fa149fe3c0c58fe3fc16d06aef8215afc/Plugin/src/main/scala/com.scalakata/ScalaKata.scala#L116

Plugin -> Backend
https://github.com/MasseGuillaume/ScalaKata/blob/753f841fa149fe3c0c58fe3fc16d06aef8215afc/Backend/src/main/scala/com.scalakata.backend/Server.scala#L12

Backend -> Compiler
https://github.com/MasseGuillaume/ScalaKata/blob/753f841fa149fe3c0c58fe3fc16d06aef8215afc/Eval/compile/src/main/scala/com.scalakata.eval/Compiler.scala#L162

**Comment by hohonuuli** [comment]
Just a note that I get the same error on Mac OS X 10.9.4 using Safari, Chrome and Firefox (with both Java 7 and 8; project is using Scala 2.11.2.)

I see you closed the issue. Is there a fix or workaround?

**Comment by MasseGuillaume** [comment]
I just label the issue as wontfix because I dont have access to a Window computer. It was tested on mac without problems. It's hard to assist you on this. You can clone this repo and do 
publishLocal on the following projects: eval, backend, plugin. See my previous comment on where the bug could be. I'm sorry I cannot do more.
