### ISSUE TITLE
Better support for ???

### ISSUE THREAD

**Issue by jedesah** [MasseGuillaume/ScalaKata#5]
(I am only putting this here for documentation purposes, I am pretty sure this is not an easy fix for you)

It would be nice if the result for this was better than an UnimplementedException

```
val a = ???
val b = 3
b
```

**Comment by MasseGuillaume** [comment]
any suggestions ?

**Comment by jedesah** [comment]
You mean from an application behaviour perspective or an implementation perspective?

**Comment by jedesah** [comment]
This should be fixed by activating that new experimental feature you integrated that some guy made. Lol!
