### ISSUE TITLE
support for print and println

### ISSUE THREAD

**Issue by adam-singer** [MasseGuillaume/ScalaKata#50]
Just started using it. Noticed that return types are printed no ability to access possible console output?

**Comment by MasseGuillaume** [comment]
I implemented tracing so the println result will be on the same line.

**Comment by adam-singer** [comment]
k, but currently on http://scalakata.com that is not happening?

**Comment by MasseGuillaume** [comment]
@financeCoding oh scalakata.com just redirect to codebrew.io for now. I did not deploy Scala Kata yet. It's now just a sbt plugin. You can try with this sample project https://github.com/ScalaKata/Scala99

**Comment by MasseGuillaume** [comment]
and this is the println code if you are curious.
https://github.com/MasseGuillaume/ScalaKata/blob/develop/Eval/macro/src/main/scala/com.scalakata.eval/package.scala#L82
https://github.com/MasseGuillaume/ScalaKata/blob/develop/Eval/macro/src/main/scala/com.scalakata.eval/Annotation.scala#L36

**Comment by adam-singer** [comment]
Nice! the `desugar` call is great to have.

**Comment by MasseGuillaume** [comment]
ty this one was simple to implement :-)
