### ISSUE TITLE
SBT Plugin does not work out of the box with multimoduled projects

### ISSUE THREAD

**Issue by vadimich** [MasseGuillaume/ScalaKata#63]
sbt plugin works well when it is setup for the main root level project, but trying to set up scalakata for a subproject in a multiproject environment with kataSettings does not work out of the box (looks like the classpath setup is not flexible enough so the Eval classes are not recognized)

**Comment by MasseGuillaume** [comment]
hum I never tested ScalaKata on a multi project. If you have time can you provide a minimal project setup that does not work. Thanks

**Comment by vadimich** [comment]
sure thing - will do it tonight
