### ISSUE TITLE
Make mongo db optional

### ISSUE THREAD

**Issue by hrj** [MasseGuillaume/ScalaKata#7]
For a quick and simple interaction, we don't need the mongo setup.

If you can make it optional, it would be great.

Also, if by default mongodb is disabled, it will be even greater!

**Comment by MasseGuillaume** [comment]
yep that's a good idea

**Comment by MasseGuillaume** [comment]
I will submit ScalaKata as a sbt plugin with 0 integration pain. Stay tuned
