### ISSUE TITLE
Please add license :)

### ISSUE THREAD

**Issue by eranation** [MasseGuillaume/ScalaKata#70]
Hi Gui,
This is simply amazing what you did with this. 
I really like the new auto completion engine etc.
p.s.
What was your open source level intended for this? 
Will you please add a license? (e.g. MIT / Apache ) 

Again, it's unbelievable what you did here. Kudos!

**Comment by MasseGuillaume** [comment]
https://github.com/MasseGuillaume/ScalaKata/blob/develop/Plugin/build.sbt#L15
