### ISSUE TITLE
Running in test environment

### ISSUE THREAD

**Issue by nightscape** [MasseGuillaume/ScalaKata#71]
Hi Guillaume,

I'm trying to run ScalaKata in test environment because I want to replicate some behaviour in test classes.
I've tried overriding lots of options along the lines of

``` scala
(fullClasspath in Kata) ++= (fullClasspath in Test).value
```

but haven't managed to get ScalaKata to run with the correct classpath.

Do you have any tips on how to get this running?

Thanks!
  Martin

**Comment by MasseGuillaume** [comment]
try

``` scala
(managedClasspath in Kata) ++= (fullClasspath in Test).value
```

the classpath passed to the server is this: https://github.com/MasseGuillaume/ScalaKata/blob/develop/Plugin/src/main/scala/com.scalakata/ScalaKata.scala#L192

**Comment by nightscape** [comment]
Doesn't seem to work unfortunately, the printed classpath doesn't list the `target/scala-2.11/test-classes` folder...
The link to the setting you mentioned seems to apply only to the Docker build, right?
I assumed this line was for running from SBT
https://github.com/MasseGuillaume/ScalaKata/blob/develop/Plugin/src/main/scala/com.scalakata/ScalaKata.scala#L95

I tried to override this in my Build.scala using

``` scala
import com.scalakata._
lazy val root = (project in file(".")).
  settings(com.scalakata.Scalakata.kataSettings: _*).
  settings(inConfig(Backend)((fullClasspath in Revolver.reStart) ++= {
    val n = (fullClasspath in Test).value
    println("Overriding with $n")
    n
  }): _*)
```

The debug statement didn't show up at all...
I also tried `managedClasspath` instead of `fullClasspath` and in `Kata` scope instead of `Backend:Revolver.reStart` and without `println` (which might interfere with SBT macros?)

**Comment by MasseGuillaume** [comment]
Ok I'm taking a look at this right now.

**Comment by MasseGuillaume** [comment]
this is the import part: https://github.com/MasseGuillaume/ScalaKata/blob/develop/Plugin/src/main/scala/com.scalakata/ScalaKata.scala#L143

to add test classes you can use this:

``` scala
dependencyClasspath in Kata ++= (fullClasspath in Test).value
```

I'm adding this to the plugin, so you will no longer need this in 0.11.0.

What do you thing of ScalaKata so far? Any requests? I'm thinking of creating a collaborative environement like google doc now.

**Comment by MasseGuillaume** [comment]
https://github.com/MasseGuillaume/ScalaKata/commit/99236912138dd79bb2ee6185a6267ccfbcf4f091#diff-fdd7f02a1f6a5fe388e8d2e743a4b891
