### ISSUE TITLE
Better parsing

### ISSUE THREAD

**Issue by jeffling** [MasseGuillaume/ScalaKata#8]
I heard from JR you tried this before but it didn't go well. Have you looked at http://jakiestfu.github.io/Behave.js/? I would like to give it a try, but if you have time to get to it first go for it.

**Comment by MasseGuillaume** [comment]
what IDE feature are you missing from the current code editor (code mirror) ?

**Comment by jeffling** [comment]
Just simple stuff like autoindenting and auto bracket completion. Looks like code mirror is capable of a lot more than what's currently being used.

**Comment by MasseGuillaume** [comment]
maybe via https://github.com/dmajda/pegjs?

look like codemirror uses incremental passes. not sure if this is possible with peg.
